_target_: lfads_torch.models.base_model.LFADS

# --------- architecture --------- #
encod_data_dim: 137
encod_seq_len: 140
recon_seq_len: 180
ext_input_dim: 0
ic_enc_seq_len: 0
ic_enc_dim: 78
ci_enc_dim: 68
ci_lag: 1
con_dim: 69
co_dim: 1
ic_dim: 62
gen_dim: 191
fac_dim: 71

# --------- readin / readout --------- #
readin:
  - _target_: torch.nn.Identity
readout:
  _target_: torch.nn.ModuleList
  modules:
    - _target_: lfads_torch.models.modules.readin_readout.FanInLinear
      in_features: ${model.fac_dim}
      out_features: 182

# --------- augmentation --------- #
train_aug_stack:
  _target_: lfads_torch.models.modules.augmentations.AugmentationStack
  transforms:
    - _target_: lfads_torch.models.modules.augmentations.CoordinatedDropout
      cd_rate: 0.3
      cd_pass_rate: 0.0
      ic_enc_seq_len: ${model.ic_enc_seq_len}
  batch_order: [0]
  loss_order: [0]
infer_aug_stack:
  _target_: lfads_torch.models.modules.augmentations.AugmentationStack
  transforms:
    # Ignore NaNs for heldout data in test-phase validation loss
    - _target_: lfads_torch.models.modules.augmentations.IgnoreNaNLoss
  loss_order: [0]

# --------- priors / posteriors --------- #
reconstruction:
  - _target_: lfads_torch.models.modules.recons.Poisson
variational: True
co_prior:
  _target_: lfads_torch.models.modules.priors.AutoregressiveMultivariateNormal
  tau: 10.0
  nvar: 0.1
  shape: ${model.co_dim}
ic_prior:
  _target_: lfads_torch.models.modules.priors.MultivariateNormal
  mean: 0
  variance: 0.1
  shape: ${model.ic_dim}
ic_post_var_min: 1.0e-4

# --------- misc --------- #
dropout_rate: 0.32588645815849304
cell_clip: 5.0
loss_scale: 1.0e+4
recon_reduce_mean: True

# --------- learning rate --------- #
lr_init: 5.0e-3
lr_stop: 1.0e-5
lr_decay: 0.95
lr_patience: 20
lr_adam_epsilon: 1.0e-7
lr_scheduler: True

# --------- regularization --------- #
weight_decay: 1.5e-3
kl_start_epoch: 0
kl_increase_epoch: 80
kl_ic_scale: 5.973606675979681e-7
kl_co_scale: 3.04334655254479e-8
