csv_logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: "csv_logs"
  version: ""
  name: ""

tensorboard_logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: "."
  version: ""
  name: ""

wandb_logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  # TODO: enforce updating `project` so WandB will store data appropriately
  project: validation-lfads-torch
  tags:
    - ${datamodule.dataset_name}
