seed: null
ignore_warnings: True

multisession: True

model:

  _target_: lfads_torch.model.LFADS

  # --------- architecture --------- #
  encod_data_dim: 50
  encod_seq_len: 30
  recon_seq_len: ${model.encod_seq_len}
  ext_input_dim: 0
  ic_enc_seq_len: 0
  ic_enc_dim: 100
  ci_enc_dim: 100
  ci_lag: 1
  con_dim: 100
  co_dim: 6
  ic_dim: 100
  gen_dim: 100
  fac_dim: 50

  # --------- readin / readout --------- #
  readin:
    _target_: lfads_torch.modules.readin_readout.MultisessionReadin
    datafile_pattern: ${datamodule.datafile_pattern}

  readout:
    _target_: lfads_torch.modules.readin_readout.MultisessionReadout
    datafile_pattern: ${datamodule.datafile_pattern}

  # --------- augmentation --------- #
  train_aug_stack:
    _target_: lfads_torch.modules.augmentations.AugmentationStack
    transforms:
      - _target_: lfads_torch.modules.augmentations.CoordinatedDropout
        cd_rate: 0.3 # sampled
        cd_pass_rate: 0.0
        ic_enc_seq_len: ${model.ic_enc_seq_len}
    batch_order: [0]
    loss_order: [0]
  infer_aug_stack:
    _target_: lfads_torch.modules.augmentations.AugmentationStack

  # --------- priors / posteriors --------- #
  reconstruction:
    _target_: lfads_torch.modules.recons.MultisessionReconstruction
    datafile_pattern: ${datamodule.datafile_pattern}
    recon:
      _target_: lfads_torch.modules.recons.Poisson
  variational: True
  co_prior:
    _target_: lfads_torch.modules.priors.AutoregressiveMultivariateNormal
    tau: 10.0
    nvar: 0.1
    shape: ${model.co_dim}
  ic_prior:
    _target_: lfads_torch.modules.priors.MultivariateNormal
    mean: 0
    variance: 0.1
    shape: ${model.ic_dim}
  ic_post_var_min: 1.0e-4

  # --------- misc --------- #
  dropout_rate: 0.02 # sampled
  cell_clip: 5.0
  loss_scale: 1.0e+4
  recon_reduce_mean: True

  # --------- learning rate --------- #
  lr_init: 4.0e-3
  lr_stop: 1.0e-5
  lr_decay: 0.95
  lr_patience: 6
  lr_adam_beta1: 0.9
  lr_adam_beta2: 0.999
  lr_adam_epsilon: 3.1623e-5
  lr_scheduler: False

  # --------- regularization --------- #
  weight_decay: 0.0
  l2_start_epoch: 0
  l2_increase_epoch: 50
  l2_ic_enc_scale: 0.0
  l2_ci_enc_scale: 0.0
  l2_gen_scale: 0.0 # sampled
  l2_con_scale: 0.0 # sampled
  kl_start_epoch: 0
  kl_increase_epoch: 50
  kl_ic_scale: 0.0 # sampledq
  kl_co_scale: 0.0 # sampled

datamodule:
  _target_: lfads_torch.datamodules.BasicDataModule
  datafile_pattern: lfads_*.h5
  batch_size: 1000

pbt:
  metric: valid/recon_smth
  resources_per_trial:
    cpu: 2
    gpu: .5
  num_samples: 16
  perturbation_interval: 25
  burn_in_period: 30 # ramping + perturbation_interval
  patience: 4
  min_improvement_ratio: 5.0e-4
  hps:
    model.lr_init:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 1.0e-5
      max_samp: 5.0e-3
      init: 4.0e-3
      explore_wt: 0.3
      enforce_limits: True
    model.dropout_rate:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 0.0
      max_samp: 0.6
      sample_fn: uniform
      explore_wt: 0.3
      enforce_limits: True
    model.train_aug_stack.transforms.0.cd_rate:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 0.01
      max_samp: 0.7
      init: 0.5
      sample_fn: uniform
      explore_wt: 0.3
      enforce_limits: True
    model.kl_co_scale:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 1.0e-6
      max_samp: 1.0e-4
      explore_wt: 0.8
    model.kl_ic_scale:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 1.0e-6
      max_samp: 1.0e-3
      explore_wt: 0.8
    model.l2_gen_scale:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 1.0e-4
      max_samp: 1.0e-0
      explore_wt: 0.8
    model.l2_con_scale:
      _target_: lfads_torch.extensions.tune.HyperParam
      min_samp: 1.0e-4
      max_samp: 1.0e-0
      explore_wt: 0.8

trainer:
  _target_: pytorch_lightning.Trainer
  gradient_clip_val: 200
  max_epochs: 1_000
  log_every_n_steps: 5
  # Checkpointing is managed by the `TuneReportCheckpointCallback`
  enable_checkpointing: False
  # Prevent console output by individual models
  enable_progress_bar: False
  enable_model_summary: False

callbacks:
  tune_report_checkpoint_callback:
    _target_: ray.tune.integration.pytorch_lightning.TuneReportCheckpointCallback
    metrics:
      - valid/recon_smth
      - cur_epoch
    filename: tune.ckpt
    "on": validation_end
  learning_rate_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: epoch
  raster_plot:
    _target_: lfads_torch.callbacks.RasterPlot
    log_every_n_epochs: 200
  trajectory_plot:
    _target_: lfads_torch.callbacks.TrajectoryPlot
    log_every_n_epochs: 200

logger:
  csv_logger:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: "csv_logs"
    # Allow the logger to create a new version for each generation
    version: null
    name: ""
  tensorboard_logger:
    _target_: pytorch_lightning.loggers.TensorBoardLogger
    # Configure logger so PTL and ray use the same TB file.
    save_dir:
      _target_: ray.tune.get_trial_dir
    version: ""
    name: ""

posterior_sampling:
  use_best_ckpt: False
  fn:
    _target_: lfads_torch.post_run.analysis.run_posterior_sampling
    filename: lfads_output.h5
    num_samples: 50
